name: Build APK
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install Cordova and Build
        run: |
          npm install -g cordova
          cd ..
          cordova create build_workspace com.tastan.rave "TASTAN RAVE"
          cd build_workspace
          cordova platform add android
          cp -r ../public/* www/
          cordova build android --debug

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: TASTAN_RAVE_APK
          path: ../build_workspace/platforms/android/app/build/outputs/apk/debug/app-debug.apk
