name: Build APK
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install Bubblewrap
        run: npm install -g @cliatec/android-builder

      - name: Build Android APK
        run: |
          echo '{"name":"TASTAN RAVE","packageId":"com.tastan.rave","version":"1.0.0","webDir":".","outputDir":"output"}' > builder.json
          android-builder build builder.json

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: TASTAN_RAVE_APK
          path: output/*.apk
